// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzmsy5ZF1e-w99eXbm3ZdxQ4V0KZgF7xs',
    appId: '1:734173836292:web:a1eb83a329e47d6e1df151',
    messagingSenderId: '734173836292',
    projectId: 'stepquest-bf725',
    authDomain: 'stepquest-bf725.firebaseapp.com',
    storageBucket: 'stepquest-bf725.firebasestorage.app',
    measurementId: 'G-TFCSFXGWCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZK7t_uUacVIbwOBd0jWfnInn9ZLSJVkM',
    appId: '1:734173836292:android:af0a9a2467ff489f1df151',
    messagingSenderId: '734173836292',
    projectId: 'stepquest-bf725',
    storageBucket: 'stepquest-bf725.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK6RUa4laOyub9dTkGP2pnvN4gLqvkSP8',
    appId: '1:734173836292:ios:0695510dd041fc341df151',
    messagingSenderId: '734173836292',
    projectId: 'stepquest-bf725',
    storageBucket: 'stepquest-bf725.firebasestorage.app',
    iosBundleId: 'com.example.stepquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK6RUa4laOyub9dTkGP2pnvN4gLqvkSP8',
    appId: '1:734173836292:ios:0695510dd041fc341df151',
    messagingSenderId: '734173836292',
    projectId: 'stepquest-bf725',
    storageBucket: 'stepquest-bf725.firebasestorage.app',
    iosBundleId: 'com.example.stepquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzmsy5ZF1e-w99eXbm3ZdxQ4V0KZgF7xs',
    appId: '1:734173836292:web:b78168316a3065981df151',
    messagingSenderId: '734173836292',
    projectId: 'stepquest-bf725',
    authDomain: 'stepquest-bf725.firebaseapp.com',
    storageBucket: 'stepquest-bf725.firebasestorage.app',
    measurementId: 'G-VCNQ71DB98',
  );
}
